LinkLuaModifier("modifier_gem1", 'modifiers/gems/gem1', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem2", 'modifiers/gems/gem2', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem3", 'modifiers/gems/gem3', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem4", 'modifiers/gems/gem4', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem5", 'modifiers/gems/gem5', LUA_MODIFIER_MOTION_NONE)
-----------------------------------------------------------------------------------------------------
LinkLuaModifier( "modifier_easy", "abilities/difficult/easy", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_normal", "abilities/difficult/normal", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_hard", "abilities/difficult/hard", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_ultra", "abilities/difficult/ultra", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_insane", "abilities/difficult/insane", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_impossible", "abilities/difficult/impossible", LUA_MODIFIER_MOTION_NONE )
-----------------------------------------------------------------------------------------------------
LinkLuaModifier( "modifier_unit_on_death", "modifiers/modifier_unit_on_death", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_unit_on_death2", "modifiers/modifier_unit_on_death2", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_creep_antilag", "modifiers/modifier_hide_zone_units", LUA_MODIFIER_MOTION_NONE )
-----------------------------------------------------------------------------------------------------
LinkLuaModifier( "modifier_attack_speed", "modifiers/modifier_attack_speed", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_spell_ampl_creep", "modifiers/modifier_spell_ampl_creep", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_health", "modifiers/modifier_health", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_hp_regen_creep", "modifiers/modifier_hp_regen_creep", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_hp_regen_commandir", "modifiers/modifier_hp_regen_commandir", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_hp_regen_boss", "modifiers/modifier_hp_regen_boss", LUA_MODIFIER_MOTION_NONE )
-----------------------------------------------------------------------------------------------------
LinkLuaModifier( "modifier_dummy", "modifiers/modifier_dummy", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_dummy_damage", "modifiers/modifier_dummy_damage", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier('modifier_high_five_custom_search', 'effects.lua', LUA_MODIFIER_MOTION_NONE)
-----------------------------------------------------------------------------------------------------
LinkLuaModifier( "modifier_base_passive", "modifiers/modifier_base", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_transformation", "modifiers/modifier_base", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_silent", "modifiers/modifier_silent", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_silent2", "modifiers/modifier_silent2", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_insane_lives", "modifiers/modifier_insane_lives", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gold_bank", "modifiers/modifier_gold_bank", LUA_MODIFIER_MOTION_NONE)
-----------------------------------------------------------------------------------------------------
LinkLuaModifier( "modifier_only_phys", "modifiers/modifier_only_phys", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier( "modifier_ban", "modifiers/modifier_ban", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier( "modifier_cheack_afk", "modifiers/modifier_cheack_afk", LUA_MODIFIER_MOTION_NONE)
-----------------------------------------------------------------------------------------------------
LinkLuaModifier( "modifier_health_voker", "modifiers/modifier_health_voker", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_health_mega", "modifiers/modifier_health_mega", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_pips", "modifiers/modifier_pips", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_generic_arc_lua", "heroes/generic/modifier_generic_arc_lua", LUA_MODIFIER_MOTION_BOTH )


LinkLuaModifier( "modifier_animation", "libraries/modifiers/modifier_animation.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_animation_translate", "libraries/modifiers/modifier_animation_translate.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_animation_translate_permanent", "libraries/modifiers/modifier_animation_translate_permanent.lua", LUA_MODIFIER_MOTION_NONE )

LinkLuaModifier( "effect_projectile_change1", "modifiers/effect_projectile_change1", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "effect_projectile_change2", "modifiers/effect_projectile_change2", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "effect_projectile_change3", "modifiers/effect_projectile_change3", LUA_MODIFIER_MOTION_NONE )


LinkLuaModifier( "modifier_minimap_icon", "modifiers/modifier_minimap_icon", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_custom_vision", "modifiers/modifier_custom_vision", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_wearable_pet", "modifiers/modifier_wearable_pet", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gold_creep", "modifiers/modifier_gold_creep", LUA_MODIFIER_MOTION_NONE )

--таланты
LinkLuaModifier( "modifier_don1", "abilities/talents/modifiers/modifier_don1", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_don2", "abilities/talents/modifiers/modifier_don2", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_don3", "abilities/talents/modifiers/modifier_don3", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_don4", "abilities/talents/modifiers/modifier_don4", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_don5", "abilities/talents/modifiers/modifier_don5", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_don6", "abilities/talents/modifiers/modifier_don6", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_don7", "abilities/talents/modifiers/modifier_don7", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_don8", "abilities/talents/modifiers/modifier_don8", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_don9", "abilities/talents/modifiers/modifier_don9", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_don10", "abilities/talents/modifiers/modifier_don10", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_don11", "abilities/talents/modifiers/modifier_don11", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_don_last", "abilities/talents/modifiers/modifier_don_last", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_don13", "abilities/talents/modifiers/modifier_don13", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_talent_sheeld", "abilities/talents/modifier_talent_sheeld", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_talent_armor_curruption", "abilities/talents/modifier_talent_armor_curruption", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_talent_armor_curruption_effect", "abilities/talents/modifier_talent_armor_curruption", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_talent_mp_regen_level", "abilities/talents/modifier_talent_mp_regen_level", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_talent_magic_damage", "abilities/talents/modifier_talent_magic_damage", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_talent_manacost", "abilities/talents/modifier_talent_manacost", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_talent_m_resist", "abilities/talents/modifier_talent_m_resist", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_talent_increase_str", "abilities/talents/modifier_talent_increase_str", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier( "modifier_talent_increase_int", "abilities/talents/modifier_talent_increase_int", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier( "modifier_talent_increase_agi", "abilities/talents/modifier_talent_increase_agi", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier( "modifier_talent_hp_regen_level", "abilities/talents/modifier_talent_hp_regen_level", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_talent_hp_per_level", "abilities/talents/modifier_talent_hp_per_level", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_talent_dmg_per_level", "abilities/talents/modifier_talent_dmg_per_level", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_talent_base_attack_time", "abilities/talents/modifier_talent_base_attack_time", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_talent_armor_per_level", "abilities/talents/modifier_talent_armor_per_level", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_talent_all_evasion", "abilities/talents/modifier_talent_all_evasion", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_talent_spectre_str3", "abilities/talents/modifier_talent_spectre_str3", LUA_MODIFIER_MOTION_NONE )


LinkLuaModifier( "modifier_rune_crit", "modifiers/runes/modifier_rune_crit", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_rune_phys_damage_increace", "modifiers/runes/modifier_rune_phys_damage_increace", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_rune_all_damage_increace", "modifiers/runes/modifier_rune_all_damage_increace", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_rune_multicast", "modifiers/runes/modifier_rune_multicast", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_rune_mage_damage_increace", "modifiers/runes/modifier_rune_mage_damage_increace", LUA_MODIFIER_MOTION_NONE )
